E2Helper.Descriptions["physgunShare"] = "shares physgun prop protection with E, equivalent to ticking the 'Physgun buddy' box in the buddies menu"
E2Helper.Descriptions["gravgunShare"] = "shares gravgun prop protection with E, equivalent to ticking the 'Gravgun buddy' box in the buddies menu"
E2Helper.Descriptions["useShare"] = "shares use prop protection with E, equivalent to ticking the 'Use buddy' box in the buddies menu"
E2Helper.Descriptions["damageShare"] = "shares damage entity prop protection with E, equivalent to ticking the 'Entity damage buddy' box in the buddies menu"
E2Helper.Descriptions["toolgunShare"] = "shares toolgun prop protection with E, equivalent to ticking the 'Toolgun buddy' box in the buddies menu"