E2Helper.Descriptions["sharePhysgun"] = "shares physgun prop protection with E, equivalent to ticking the 'Physgun buddy' box in the buddies menu"
E2Helper.Descriptions["shareGravgun"] = "shares gravgun prop protection with E, equivalent to ticking the 'Gravgun buddy' box in the buddies menu"
E2Helper.Descriptions["shareUse"] = "shares use prop protection with E, equivalent to ticking the 'Use buddy' box in the buddies menu"
E2Helper.Descriptions["shareDamage"] = "shares damage entity prop protection with E, equivalent to ticking the 'Entity damage buddy' box in the buddies menu"
E2Helper.Descriptions["shareToolgun"] = "shares toolgun prop protection with E, equivalent to ticking the 'Toolgun buddy' box in the buddies menu"